DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS SEATING_CHART;

CREATE TABLE SEATING_CHART (
    FLOOR_SEAT_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO VARCHAR(20) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    FLOOR_SEAT_SEQ BIGINT,
    CONSTRAINT FK_EMP_SEAT
        FOREIGN KEY (FLOOR_SEAT_SEQ)
        REFERENCES SEATING_CHART(FLOOR_SEAT_SEQ)
);
